### ISSUE TITLE
Error: No router instance found.

### ISSUE THREAD

**Issue by firozansari** [zvikfir/MyWay#22]
Thank you so much to resolve the previous issue. I just took the latest version from the master branch. I am able to compile the code successfully but I am getting an error if I access any page (for example home page) on the browser. the Server instance just crash.

```
D:\Learning\MyWay\MyWay-client>npm run dev

> client-nextjs@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from D:\Learning\MyWay\MyWay-client\.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /dogs
wait  - compiling...
event - compiled successfully
D:\Learning\MyWay\MyWay-client\node_modules\next\dist\client\router.js:116
        throw new Error(message);
              ^

Error: No router instance found.
You should only use "next/router" on the client side of your app.

    at getRouter (D:\Learning\MyWay\MyWay-client\node_modules\next\dist\client\router.js:116:15)
    at Object.singletonRouter.<computed> [as push] (D:\Learning\MyWay\MyWay-client\node_modules\next\dist\client\router.js:93:24)
    at D:\Learning\MyWay\MyWay-client\.next\server\pages\_app.js:2705:176
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by zvikfir** [comment]
Hi @firozansari,

Thanks a lot for your help. It took me some time but I was finally able to fix this issue. 

It seems that code that is run outside a function component of React could run on the backend as well as on the frontend. This occurs due to the pre-rendering that NextJS performs.

I added a condition to the use of the `Router.push` function in the service classes, which fixed the issue.

I took the solution from [here](https://stackoverflow.com/questions/49074986/redirecting-from-getinitalprops-in-react-next-js).

You will also see that the language of the website is now changed to Hebrew. While interviewing Israeli dog trainers as part of the UI/UX design process, we found that a website in English will probably not be useful to them. I can't tell for sure, but we might also make an English version in the future.
